FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_PUBLIC_APP_URL
ARG VITE_EVOLUTION_URL
ARG VITE_EVOLUTION_API_KEY
ARG VITE_EVOLUTION_INSTANCE_NAME
ARG VITE_EVOLUTION_API_PREFIX
ARG VITE_EVOLUTION_WEBHOOK_PATH
ARG VITE_EVOLUTION_WEBHOOK_URL

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_PUBLIC_APP_URL=$VITE_PUBLIC_APP_URL
ENV VITE_EVOLUTION_URL=$VITE_EVOLUTION_URL
ENV VITE_EVOLUTION_API_KEY=$VITE_EVOLUTION_API_KEY
ENV VITE_EVOLUTION_INSTANCE_NAME=$VITE_EVOLUTION_INSTANCE_NAME
ENV VITE_EVOLUTION_API_PREFIX=$VITE_EVOLUTION_API_PREFIX
ENV VITE_EVOLUTION_WEBHOOK_PATH=$VITE_EVOLUTION_WEBHOOK_PATH
ENV VITE_EVOLUTION_WEBHOOK_URL=$VITE_EVOLUTION_WEBHOOK_URL

RUN npm run build

FROM node:22-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/dist ./dist

EXPOSE 4173

CMD ["serve", "-s", "dist", "-l", "4173"]
